/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 50431
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Expediente = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        Registro = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        JB_Exit0 = new javax.swing.JButton();
        JB_Registro = new javax.swing.JButton();
        JB_Expediente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        Expediente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/812441.png"))); // NOI18N
        Expediente.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 280, 270));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bluevector.jpg"))); // NOI18N
        Fondo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Expediente.getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 690));

        Registro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/812441.png"))); // NOI18N
        Registro.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 270));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bluevector.jpg"))); // NOI18N
        Fondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Registro.getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 690));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_Exit0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/Exit0.png"))); // NOI18N
        JB_Exit0.setBorder(null);
        JB_Exit0.setContentAreaFilled(false);
        JB_Exit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Exit0ActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Exit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 60, 60));

        JB_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/big New Person.png"))); // NOI18N
        JB_Registro.setBorder(null);
        JB_Registro.setContentAreaFilled(false);
        getContentPane().add(JB_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 330, 270));

        JB_Expediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/Big Files.png"))); // NOI18N
        JB_Expediente.setBorder(null);
        JB_Expediente.setContentAreaFilled(false);
        getContentPane().add(JB_Expediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 330, 270));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel4.setText("Expedientes");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 330, 60));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel5.setText("Registro");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 240, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/812441.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 280, 270));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bluevector.jpg"))); // NOI18N
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_Exit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Exit0ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JB_Exit0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Expediente;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JButton JB_Exit0;
    private javax.swing.JButton JB_Expediente;
    private javax.swing.JButton JB_Registro;
    private javax.swing.JDialog Registro;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
